--- 
abstract: a simple finger server
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.000
license: perl
name: Net-Finger-Server
requires: 
  Net::Server: 0
  Package::Generator: 0
  Sub::Exporter: 0
version: 0.003
